### ISSUE TITLE
How do you make the New-Tab to homepage work ?

### ISSUE THREAD

**Issue by Aristoxenos** [Catgrills/Nano#1]
Hi there,
in your instruction you explain that by downloading the Add-On "new-tab-homepage" the homepage will open in  new tabs. I tested it and it doesnt work. So, is there a trick I'm not aware or is the instruction outdated. 

I hope I dont bother you and keep up the nice work. You have some incredible stuff.

Best regards

Aristoxenos

**Comment by Catgrills** [comment]
Hey Aristoxenos,

Actually, the instructions are outdated (for FF at least), I will rewrite them soon enough. I presume you're on the latest version of Mozilla, then you can : 
1) Download the add-on called New Tab Override : https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/
2) Set your startpage online, you can use github pages : https://pages.github.com/
3) Set your startpage as your default homepage, then go to New Tab Override Settings and Select 'Current Homepage'
